# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 00:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_No', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Rubi_food Category', max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('category_image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='Rubi_specials', max_length=25)),
                ('food_description', models.TextField(max_length=200)),
                ('quantity_available', models.IntegerField(default=0)),
                ('food_image', models.ImageField(upload_to='media/')),
                ('on_offer', models.BooleanField(default=False)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubi_food.Category', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORD_No', models.CharField(default=datetime.datetime(2018, 3, 13, 0, 54, 51, 993462), max_length=255)),
                ('destination_addr', models.CharField(default='Nairobi CBD', max_length=80)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('rating', models.FloatField(default=0.0, null=True)),
                ('food_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rubi_food.Food')),
            ],
        ),
    ]
