# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rubi_food', '0003_auto_20180313_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 16, 27, 36, 520862, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ORD_No',
            field=models.CharField(default=datetime.datetime(2018, 3, 13, 16, 27, 36, 522722), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 16, 27, 36, 522875, tzinfo=utc)),
        ),
    ]
