# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rubi_food', '0006_auto_20180315_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food_id',
            new_name='foodid',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 20, 39, 20, 125269, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 20, 39, 20, 122407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ORD_No',
            field=models.CharField(default=datetime.datetime(2018, 3, 15, 20, 39, 20, 124358), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 20, 39, 20, 124536, tzinfo=utc)),
        ),
    ]
