# Generated by Django 2.0.5 on 2018-05-04 05:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubi_food', '0009_auto_20180323_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('location', models.CharField(max_length=80)),
                ('mobile_contact', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number in the format +254700000000', max_length=128)),
                ('reg_timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_No',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 5, 24, 38, 95099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 5, 24, 38, 91835, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ORD_No',
            field=models.CharField(default=datetime.datetime(2018, 5, 4, 5, 24, 38, 94056), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 5, 24, 38, 94290, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='accounts',
            name='cart_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubi_food.Cart'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubi_food.Customer'),
        ),
    ]
