# Generated by Django 2.0.5 on 2018-05-04 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rubi_food', '0015_auto_20180504_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 17, 33, 51, 323505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 17, 33, 51, 320597, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(default='Rubi_specials', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='ORD_No',
            field=models.CharField(default=datetime.datetime(2018, 5, 4, 17, 33, 51, 322673), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 17, 33, 51, 322873, tzinfo=utc)),
        ),
    ]
